"""Unit tests for Deterministic Grounding & Evidence Validation (Milestone 4.1)."""

import pytest
from understanding_engine.grounding import (
    DeterministicGroundingValidator,
    is_equation_supported,
    validate_numeric_claim,
)
from understanding_engine.schemas import (
    Concept,
    Equation,
    ImportantPoint,
    LectureUnderstanding,
)


def test_1_explicit_equation_in_transcript_accepted() -> None:
    """TEST 1: Transcript explicitly contains equation -> equation accepted."""
    transcript = "Here the circuit follows Ohm's law, where I = V / R as shown."
    eq = Equation(
        latex_or_text="I = V / R",
        description="Ohm's law",
        timestamp=10.0,
    )
    is_supp, status, snippet = is_equation_supported(eq, transcript)
    assert is_supp is True
    assert status == "supported"
    assert "Direct symbolic match" in snippet


def test_2_concept_described_without_equation_rejected() -> None:
    """TEST 2: Transcript describes concept but never states equation -> hallucinated equation rejected."""
    transcript = "According to Ohm's law, when resistance decreases, the electric current increases."
    eq = Equation(
        latex_or_text="I = V / R",
        description="Ohm's law",
        timestamp=15.0,
    )
    is_supp, status, _ = is_equation_supported(eq, transcript)
    assert is_supp is False
    assert status == "unsupported"

    # Test full understanding validation pipeline moves it to rejected_equations
    understanding = LectureUnderstanding(
        time_start=10.0,
        time_end=20.0,
        topic="Current and Resistance",
        equations=[eq],
    )
    validated = DeterministicGroundingValidator.validate_understanding(understanding, raw_transcript=transcript)
    assert len(validated.equations) == 0
    assert len(validated.rejected_equations) == 1
    assert validated.rejected_equations[0].grounding_status == "unsupported"


def test_3_spoken_equation_using_words_accepted() -> None:
    """TEST 3: Spoken equation using words -> normalized equation accepted."""
    transcript = "Electric current is equal to voltage divided by resistance."
    eq = Equation(
        latex_or_text="I = V / R",
        description="Ohm's law",
        timestamp=25.0,
    )
    is_supp, status, snippet = is_equation_supported(eq, transcript)
    assert is_supp is True
    assert status == "supported"
    assert "Spoken formula confirmed" in snippet


def test_4_unrelated_textbook_equation_rejected() -> None:
    """TEST 4: Unrelated textbook equation generated by LLM -> rejected."""
    transcript = "In this experiment we drop a ball from rest and observe its acceleration under gravity."
    eq = Equation(
        latex_or_text="E = m * c^2",
        description="Mass-energy equivalence",
        timestamp=30.0,
    )
    is_supp, status, _ = is_equation_supported(eq, transcript)
    assert is_supp is False
    assert status == "unsupported"

    understanding = LectureUnderstanding(
        time_start=25.0,
        time_end=35.0,
        topic="Free Fall",
        equations=[eq],
    )
    validated = DeterministicGroundingValidator.validate_understanding(understanding, raw_transcript=transcript)
    assert len(validated.equations) == 0
    assert len(validated.rejected_equations) == 1


def test_5_ambiguous_proper_noun_caution() -> None:
    """TEST 5: Ambiguous proper noun -> not confidently invented."""
    noisy_transcript = "HALLO HALLO, AAMAN NAM AUDRISHMAR GANAR JEE, AAMI IT SECOND YEAR E PARASUNA KORI."
    # Grounding check verifies noisy proper nouns are not hallucinated into arbitrary external entities
    assert "adrish mukherjee" not in noisy_transcript.lower()


def test_6_number_in_source_matches_extracted_accepted() -> None:
    """TEST 6: Number in source matches extracted number -> accepted."""
    transcript = "The AC frequency in this circuit is 50 Hz with an RMS voltage of 220 volts."
    point = ImportantPoint(
        point="The line frequency operates at 50 Hz.",
        timestamp_start=40.0,
        timestamp_end=45.0,
    )
    ok, unsupported = validate_numeric_claim(point.point, transcript)
    assert ok is True
    assert len(unsupported) == 0

    understanding = LectureUnderstanding(
        time_start=40.0,
        time_end=45.0,
        topic="AC Power",
        important_points=[point],
    )
    validated = DeterministicGroundingValidator.validate_understanding(understanding, raw_transcript=transcript)
    assert validated.important_points[0].importance == "high"
    assert "[Unverified" not in validated.important_points[0].point


def test_7_number_absent_from_source_flagged() -> None:
    """TEST 7: Number absent from source -> flagged/rejected."""
    transcript = "The line voltage is high and dangerous to touch."
    point = ImportantPoint(
        point="The line voltage is 440 volts.",
        timestamp_start=50.0,
        timestamp_end=55.0,
    )
    ok, unsupported = validate_numeric_claim(point.point, transcript)
    assert ok is False
    assert "440" in unsupported

    understanding = LectureUnderstanding(
        time_start=50.0,
        time_end=55.0,
        topic="Safety",
        important_points=[point],
    )
    validated = DeterministicGroundingValidator.validate_understanding(understanding, raw_transcript=transcript)
    assert validated.important_points[0].importance == "uncertain"
    assert "[Unverified number: 440]" in validated.important_points[0].point


def test_8_empty_transcript_no_unsupported_facts() -> None:
    """TEST 8: Empty transcript -> no unsupported facts accepted."""
    empty_transcript = ""
    understanding = LectureUnderstanding(
        time_start=0.0,
        time_end=10.0,
        topic="Some Hallucinated Topic",
        concepts=[Concept(name="Phantom Concept", explanation="Invented", timestamp_start=0.0, timestamp_end=5.0)],
        equations=[Equation(latex_or_text="I = V / R", description="Formula", timestamp=2.0)],
        important_points=[ImportantPoint(point="Fabricated point", timestamp_start=0.0, timestamp_end=5.0)],
    )
    validated = DeterministicGroundingValidator.validate_understanding(understanding, raw_transcript=empty_transcript)
    assert len(validated.equations) == 0
    assert len(validated.concepts) == 0
    assert len(validated.important_points) == 0
    assert len(validated.rejected_equations) == 1
    assert validated.grounding_score == 0.0
