"""Deterministic validators for VLM proposals against immutable OCR ground truth."""

from typing import List, Optional, Tuple
from evidence_fusion.matcher import DeterministicMathMatcher
from .schemas import DiagramType, VLMValidationStatus, VisualReasoningProposal


class VisualReasoningValidator:
    """Validates VLM semantic proposals against raw immutable OCR evidence."""

    def __init__(self, uncertainty_threshold: float = 0.45) -> None:
        self.uncertainty_threshold = uncertainty_threshold

    def validate_proposal(
        self,
        proposal: Optional[VisualReasoningProposal],
        raw_ocr_text: Optional[str] = None,
        ocr_equations: Optional[List[str]] = None,
        is_empty_image: bool = False,
    ) -> Tuple[VLMValidationStatus, Optional[str]]:
        """Evaluates proposal against raw OCR ground truth.

        Returns:
            (VLMValidationStatus, conflict_notes)
        """
        if is_empty_image:
            return VLMValidationStatus.EMPTY_IMAGE, "Image is empty/blank; VLM proposal ignored."

        if proposal is None:
            return VLMValidationStatus.REJECTED, "No proposal generated by provider."

        if proposal.confidence < self.uncertainty_threshold:
            return (
                VLMValidationStatus.UNCERTAIN,
                f"VLM confidence ({proposal.confidence:.2f}) below threshold ({self.uncertainty_threshold:.2f}).",
            )

        ocr_eqs = ocr_equations or []
        vlm_eqs = proposal.visible_equations

        # Check for direct mathematical contradiction with OCR evidence
        if ocr_eqs and vlm_eqs:
            for ocr_eq in ocr_eqs:
                for vlm_eq in vlm_eqs:
                    is_match, is_conflict, reason = DeterministicMathMatcher.compare_equations(
                        vlm_eq, ocr_eq
                    )
                    if is_conflict:
                        return (
                            VLMValidationStatus.OCR_CONFLICT,
                            f"VLM claimed formula '{vlm_eq}' which directly contradicts OCR ground truth '{ocr_eq}'. Raw OCR preserved.",
                        )
                    if is_match:
                        return (
                            VLMValidationStatus.VALIDATED,
                            f"VLM diagram analysis and OCR text agree on formula '{ocr_eq}'.",
                        )

        # If VLM identified a structured diagram (e.g. circuit, plot, graph)
        if proposal.diagram_type != DiagramType.NO_DIAGRAM:
            return (
                VLMValidationStatus.PROPOSED,
                f"Visual reasoning proposal registered for diagram type: '{proposal.diagram_type.value}'.",
            )

        return VLMValidationStatus.VALIDATED, "Visual proposal validated."
